FROM mysql:8.4

ENV TZ=Asia/Shanghai

RUN set -eux; \
    { \
        echo '[mysqld]'; \
        echo 'character-set-server=utf8mb4'; \
        echo 'collation-server=utf8mb4_unicode_ci'; \
        echo 'default-time-zone=+08:00'; \
        echo ''; \
        echo '[client]'; \
        echo 'default-character-set=utf8mb4'; \
    } > /etc/mysql/conf.d/dev.cnf

EXPOSE 3306
